config/routes.rb
Rails.application.routes.draw do
  post 'seen_movie/create'

  resources :seen_movie, only: [:destroy]

  post 'watchlist_item/create'
  resources :watchlist_item, only: [:destroy]

  get 'profile/', to: 'user#index', as: 'profile'
  get 'watchlist/:id', to: 'user#watch_list'

  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: %i[create destroy]
  resource :home, only: [:show]

  resources :movie
  root 'movie#index'
  get 'about/', to: 'movie#about', as: 'about'
end

app/models/movie.rb
class Movie
  def get_movie_results(genre_id)
    movie_results = HTTParty.get("http://api.themoviedb.org/3/discover/movie?with_genres=#{genre_id}&api_key=#{ENV['MOVIE_API_KEY']}&sort_by=popularity.desc")
    JSON.parse(movie_results.body)
  end

  def self.genres
    {
      28 => 'Action',
      12 => 'Adventure',
      16 => 'Animation',
      35 => 'Comedy',
      80 => 'Crime',
      18 => 'Drama',
      10751 => 'Family',
      14 => 'Fantasy',
      10769 => 'Foreign',
      36 => 'History',
      27 => 'Horror',
      10402 => 'Music',
      9648 => 'Mystery',
      10749 => 'Romance',
      878 => 'Science Fiction',
      10770 => 'TV Movie',
      53 => 'Thriller',
      10752 => 'War',
      37 => 'Western'
    }
  end

  def self.find_genre(id)
    genres = Movie.genres
    genres[id.to_i]
  end
end

app/models/seen_movie.rb
class SeenMovie < ActiveRecord::Base
  validates_uniqueness_of :movie_title, scope: :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.profile_picture = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  has_many :watchlist_items
  has_many :seen_movies
end

app/models/watchlist_item.rb
class WatchlistItem < ActiveRecord::Base
  validates_uniqueness_of :movie_title, scope: :user
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue
    false
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  def index
    @genres ||= Movie.genres
  end

  def show
    @movie_results ||= Movie.new
    @genre = Movie.find_genre(params[:id])
    @movie_results = @movie_results.get_movie_results(params[:id])
    @movie_results = @movie_results['results']

    seem_movie_gen if current_user
  end

  def about; end

  private

  def seem_movie_gen
    @watchlist_items ||= current_user.watchlist_items
    @seen_movies ||= current_user.seen_movies
    seen_movie_titles = []

    @seen_movies.each do |movie|
      seen_movie_titles << movie.movie_title
    end

    @movie_results.delete_if { |h| seen_movie_titles.include? h['title'] }
  end
end

app/controllers/seen_movie_controller.rb
class SeenMovieController < ApplicationController
  def create
    @seen_movie = SeenMovie.new(seen_movie_params)

    if @seen_movie.save
      render json: @seen_movie
    else
      render json: @seen_movie.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @seen_movie = SeenMovie.find(params[:id])
    @seen_movie.destroy
    head :no_content
  end

  private

  def seen_movie_params
    params.require(:seen_movie).permit(:movie_title, :poster,
                                       :overview, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    if !current_user
      redirect_to root_path
    else
      @watchlist_items ||= current_user.watchlist_items
      @seen_movies ||= current_user.seen_movies
      @user_name ||= current_user.name
      @profile_pic ||= serve_over_https(current_user.profile_picture)
    end
  end

  def watch_list
    user = User.find_by(uid: params[:id])
    if user
      @user_name = user.name
      @profile_pic = serve_over_https(user.profile_picture)
      @public_watchlist_items = user.watchlist_items
    else
      redirect_to root_path
    end
  end

  private

  def serve_over_https(pic)
    pic.include?('http:') ? pic.sub('http', 'https') : pic
  end
end

app/controllers/watchlist_item_controller.rb
class WatchlistItemController < ApplicationController
  def create
    @watchlist_item = WatchlistItem.new(watch_item_params)

    if @watchlist_item.save
      render json: @watchlist_item
    else
      render json: @watchlist_item.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @watchlist_item = WatchlistItem.find(params[:id])
    @watchlist_item.destroy
    head :no_content
  end

  private

    def watch_item_params
      params.require(:watchlist_item).permit(:movie_title, :poster, :overview, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/seen_movie_helper.rb
module SeenMovieHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/watchlist_item_helper.rb
module WatchlistItemHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieTo.Watch</title>
  <meta name="description"
        content="Let us decide what movie for you to watch. Share your watchlists with your friends" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'film.png' %>
  <meta property="og:url"           content="<%= root_path %>" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="movieTo.Watch" />
  <meta property="og:description"   content="Let us decide what movie for you to watch. Share your watchlists with your friends" />
  <meta property="og:image"         content="https://s3-us-west-2.amazonaws.com/moviewatchimages/movieToWatchLogo.png" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-72329503-2', 'auto');
  ga('send', 'pageview');

  </script>
  <%= csrf_meta_tags %>
</head>
<body>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '551107808409493',
        xfbml      : true,
        version    : 'v2.9'
      });
      FB.AppEvents.logPageView();
    };

    (function(d, s, id){
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>
  <ul id="dropdown1" class="dropdown-content">
    <li><a href="<%= profile_path %>">Profile</a></li>
    <li>
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
    </li>
  </ul>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <a href="<%= root_path %>" class="brand-logo">movieTo.Watch</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse">
          <i class="material-icons">menu</i>
        </a>
        <ul class="right hide-on-med-and-down">
          <% unless current_page?(root_url)   %>
            <li><a href="<%= root_path %>">Pick a Genre</a></li>
          <% end  %>
          <% if current_user %>
            <li>
              <a class="dropdown-button" href="#!" data-activates="dropdown1">
                <%= current_user.name %>
                <i class="material-icons right">arrow_drop_down</i>
              </a>
            </li>
            <% else %>
              <li>
                <%= link_to 'Sign in with <i class="fa fa-facebook-square" aria-hidden="true"></i>'.html_safe,
                            "/auth/facebook", id: "sign_in" %>
              </li>
          <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <% if current_user %>
            <li>
              <a href="<%= profile_path %>"><%= current_user.name %></a>
            </li>
            <li class="divider"></li>
            <% unless current_page?(root_url)  %>
              <li><a href="<%= root_path %>">Pick a Genre</a></li>
            <% end  %>
            <li>
              <a href="<%= profile_path %>">Profile</a>
            </li>
            <li>
              <%= link_to "Sign out", signout_path, id: "sign_out" %>
            </li>
            <% else %>
              <li>
                <%= link_to 'Sign in with <i class="fa fa-facebook-square" aria-hidden="true"></i>'.html_safe, "/auth/facebook", id: "sign_in" %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">


    <%= yield %>
  </div>
  <footer class="page-footer">
    <div class="footer-copyright">
      <div class="container">
        ©<%= Time.now.year %> - movieTo.Watch
        |  <%= link_to "About", about_path, id: "about-link" %>
        <span class="right">
          Made with <i class="fa fa-heart red-text text-darken-4" aria-hidden="true"></i>
          by
          <a class="grey-text text-lighten-4" href="http://cameroneckelberry.com/"
             target="_blank">
             Cameron Eckelberry
          </a>
       </span>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/movie/about.html.erb
<div class="row">
  <div class="col s12">
    <h1 class="responsize-header">About movieTo.Watch</h1>
  </div>
  <div class="col m12 s12">
    <p class="flow-text">
      My family and I love movies. As a matter of fact we watch a movie
      together every week.<br />
      Being a big family, we often run into the question,<br />
      <strong>"What movie do you want to watch?"</strong>
    </p>
    <p class="flow-text">
      I hope this app answers that question for us 😁 .
    </p>
      <p>
        <%= image_tag 'themoviedb.png', alt: "theMovieDB Logo", class: "responsive-image" %>
      </p>
  </div>

</div>

app/views/movie/index.html.erb
<%= react_component 'Movies', { genres: @genres, root: root_path } %>

app/views/movie/show.html.erb
<% if current_user  %>
  <% user_id = current_user.id %>
  <% fb_id = current_user.uid  %>
<% end  %>  
<%=
  react_component 'Results', { movies: @movie_results,
                               watchListItems: @watchlist_items,
                               user_id: user_id,
                               fbId: fb_id,
                               genre: @genre,
                             }
%>

app/views/user/index.html.erb
<div class="row">
  <div class="col s12 m12">
    <h2>
      <img src="<%= @profile_pic %>"
           alt="<%= @user_name %>"
           class="circle" />
      <%= current_user.name %>
    </h2>
  </div>
</div>

<%=
  react_component 'ProfileMovieList', {
                                        watchListItems: @watchlist_items,
                                        user_id: current_user.id,
                                        seenMovies: @seen_movies,
                                        fbId: current_user.uid
                                      }
%>

app/views/user/watch_list.html.erb
<div class="row">
  <div class="col s12 center">
    <h1>
      <img src="<%= @profile_pic %>" class="circle" alt="<%= @user_name %>'s profile picture">
      <%= @user_name %>
    </h1>
  </div>
</div>
<%= react_component 'sharableMovieList', { watchListItems: @public_watchlist_items } %>